[project]
name = "ai-researchassitant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "camel-ai[all]>=0.2.37",
    "pre-commit>=3.8.0",
]
